### ISSUE TITLE
Powershell issue when attempting to launch bot.

### ISSUE THREAD

**Issue by SnickeredMG** [nishi7409/ClanLabs-OpenSourced#11]
`ReferenceError: config is not defined
    at Object.<anonymous> (C:\Users\snickeredyt\Desktop\ageisTest\aegis_core_code.js:25:24)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

C:\Users\snickeredyt\Desktop\ageisTest>`

Thats the error I'm getting but I'm not quite sure why and or what is missing.

`// READY EVENT [START]
aegisAutomation.on('ready', () => {
  console.log('Turned on Discord bot');
  aegisAutomation.user.setActivity(`${aegisAutomation.users.size} soldiers`, { type: 'PREFIX = ! | WATCHING' })
  aegisAutomation.user.setAvatar(`https://cdn.discordapp.com/attachments/475855258191659019/553752038303858738/aegis_logo.png`)
})
// READY EVENT [END]`
Thats what is at Line 22- Line 28.

**Comment by nishi7409** [comment]
Please follow the tutorial found in the README.md file.
